name: "Action"

inputs:
  load_balancer:
    description: "Load balancer name"
    required: true
  naked_domain:
    description: "Naked domain"
    required: true
  project_id:
    description: "Project ID"
    required: true
  deployment_bucket:
    description: "Deployment bucket"
    required: true
  operation:
    description: "Action inputs"
    required: true
  type: 
    description: "Type of operation"
    required: true
  location:
    description: "Location information"
    required: true
  name:
    description: "Name"
    required: true
  path:
    description: "File path"
    required: true
  subdomain:
    description: "Subdomain"
    required: false
  database:
    description: "Database name"
    required: false
  vpc_connector:
    description: "VPC connector name"
    required: false
  environment:
    description: "Environment name"
    required: false
  instances: 
    description: "Number of instances"
    required: false
    default: 0
  template: 
    description: "Template name"
    required: false

runs:
  using: "node20"
  main: "./index.js"
  # action scripts